SELECT * FROM customer
--What is the total revenue generated by male vs. female customers?
SELECT gender, SUM("purchase_amount_(usd)") as revenue
from customer
GROUP BY gender

--which customer used a discount but stil spent more than the average purchase amount?
SELECT customer_id, "purchase_amount_(usd)"
FROM customer
WHERE discount_applied = 'Yes' AND "purchase_amount_(usd)" >= (SELECT AVG("purchase_amount_(usd)") FROM customer)

--which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--Compare the average Purchase amount between standard and express shipping
SELECT shipping_type,
ROUND(AVG("purchase_amount_(usd)"), 2)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type

--Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG("purchase_amount_(usd)"), 2) AS avg_spend,
ROUND(SUM("purchase_amount_(usd)")) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

--Which 5 products have the highest percentage of purchase with discounts applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Segment customers into NEW, Returning, and loyal based on their total number of previous purchase, and show the count of each segement
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'LOYAL'
	END AS customer_segment
FROM customer
)

SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment

--What are the top three mosy purchased products within each catogery
WITH item_counts AS (
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

--Are customers who are repeat buyers ( more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

--What is the revenue contribution of each age group?
SELECT age_group,
SUM("purchase_amount_(usd)") as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;